repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
# DEVELOPER NOTE: My machine is running a very slow HDD, and compiling the entire build at each commit takes an exponentional amount of time
# I am commenting this out until I get an NVME SSD which would significantly improve build times and allow less annoynance
# - repo: https://github.com/est31/cargo-udeps
#   rev: v0.1.47
#   hooks:
#   - id: udeps
