cargo-features = ["profile-rustflags"]

[package]
name = "protein"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- Base API Requirement
rocket = { version = "0.5.1", features = ["json", "uuid"] }
rocket-client-addr = { git = "https://github.com/guenhter/rocket-client-addr", version = "*" }
rocket-governor = { version = "0.2.0-rc.4", features = [
    "logger",
    "limit_info",
] }
rocket_prometheus = "0.10.1"
# -- Diesel Requirements (Database)
diesel = { version = "2.2.7", features = [
    "postgres",
    "uuid",
    "chrono",
    "numeric"
] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel-async = { version = "0.5.2", features = [
    "postgres",
    "deadpool",
    "async-connection-wrapper",
] }
diesel_migrations = { version = "2.2.0" }
# -- Async
tokio-cron-scheduler = {version = "0.13.0", features = ["signal", "english"]}
# -- Serialization
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.13.2", features = ["fast-rng"] }
chrono = { version = "0.4.39", features = ["serde"] }
user-agent-parser = {version = "0.3.6", features = ["rocket"]}
# -- Validation
validator = { version = "0.20.0", features = ["derive"] }
# -- Passwords
rust-argon2 = "2.1"
# -- .env
dotenvy = "0.15.7"
# -- Tracing
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"]}
tracing-appender = "0.2.3"
# -- Redis
fred = { version = "10.0.4", features = ["serde-json", "i-keys"] }
## -- Sentry
rocket-sentry = "0.18.0"
## -- Emailing
lettre = { version = "0.11", features = [
    "tokio1",
    "tokio1-native-tls",
    "serde",
] }

[workspace.metadata.typos]
files.extend-exclude = ["regexes.yaml"]

[package.metadata.cargo-machete]
ignored = ["rust-argon2"]
