cargo-features = ["profile-rustflags"]

[package]
name = "protein"
version = "0.1.0"
edition = "2024"

[dependencies]
# -- Base API Requirement
rocket = { version = "0.5.1", features = ["json", "uuid"] }
rocket-client-addr = { git = "https://github.com/Frauscher-Sensortechnology/rocket-client-addr", version = "*" }
rocket-governor = { version = "0.2.0-rc.4", features = [
    "logger",
    "limit_info",
] }
rocket_prometheus = "0.10.1"
async-fs = "2.1.2"
# -- Diesel Requirements (Database)
diesel = { version = "2.2.10", features = [
    "postgres",
    "uuid",
    "chrono",
    "postgres_backend",
] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel-async = { version = "0.5.2", features = [
    "postgres",
    "deadpool",
    "async-connection-wrapper",
] }
diesel_migrations = { version = "2.2.0" }
# -- Async
tokio-cron-scheduler = { version = "0.14.0", features = ["signal", "english"] }
# -- Serialization
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17.0", features = ["fast-rng"] }
chrono = { version = "0.4.44", features = ["serde"] }
user-agent-parser = { version = "0.3.6", features = ["rocket"] }
iso8061-timestamp = "0.1"
# -- Validation
validator = { version = "0.20.0", features = ["derive"] }
# -- Passwords
rust-argon2 = "2.1"
# -- .env
dotenvy = "0.15.7"
# -- Tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-appender = "0.2.3"
# -- Redis
fred = { version = "10.1.0", features = ["serde-json", "i-keys"] }
## -- Communication
rocket-sentry = "0.20.0"
discord-webhook2 = "0.4.3"
## -- Emailing
askama = "0.14.0"
lettre = { version = "0.11.15", features = ["tokio1", "tokio1-native-tls"] }
# -- Random
rand = "0.9.1"

[workspace.metadata.typos]
files.extend-exclude = ["regexes.yaml"]

[package.metadata.cargo-machete]
ignored = ["rust-argon2"]
