cargo-features = ["profile-rustflags"]

[package]
name = "protein"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
# -- Base API Requirement
rocket = { version = "0.5.1", features = ["json", "uuid"] }
# -- Diesel Requirements (Database)
diesel = { version = "2.2.6", features = ["postgres", "uuid", "chrono"] }
diesel-async = { version = "0.5.2", features = [
    "postgres",
    "deadpool",
    "async-connection-wrapper",
] }
diesel_migrations = { version = "2.2.0" }
# -- Serialization
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.12.0", features = ["fast-rng"] }
chrono = { version = "0.4.39", features = ["serde"] }
# -- .env
dotenvy = "0.15"
# -- Tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2.3"
# -- Redis
fred = { version = "10.0.3", features = ["serde-json", "i-keys"] }
## -- Shadow and SysInfo
shadow-rs = { version = "0.37.0", features = ["metadata"] }
sysinfo = "0.33.1"
## -- Sentry
rocket-sentry = "0.18.0"

[build-dependencies]
shadow-rs = { version = "0.37.0", features = ["metadata"] }
