services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ghoul
      POSTGRES_DB: mei
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data 

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://ghoul:password@db/mei
    ports:
      - "8000:5000"


  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
 
volumes:
  pgdata: