name: protein

services:
  db:
    container_name: hypertrophy-database
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_USER: ghoul
      POSTGRES_DB: mei
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  api:
    container_name: hypertrophy-api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    env_file:
      - docker.env
    ports:
      - "8000:5000"
    restart: unless-stopped

  redis:
    container_name: hypertrophy-redis
    image: "redis:7-alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5

volumes:
  pgdata: {}
  redis_data: {}