name: protein

services:
  db:
    container_name: storage
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: stamina
      POSTGRES_PASSWORD: password
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - server

  backup_db:
    container_name: backup_db
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: pgbackweb
      POSTGRES_PASSWORD: password
    user: postgres
    volumes:
      - backup_pgdata:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - "5200:5432"
    restart: unless-stopped
    profiles:
      - server

  backup:
    container_name: backup
    image: eduardolat/pgbackweb:latest
    ports:
      - "8085:8085"
    volumes:
      - ./backups:/backups
    environment:
      PBW_ENCRYPTION_KEY: ${POSTGRES_BACKUP_ENCRYPTION_KEY}
      PBW_POSTGRES_CONN_STRING: postgres://postgres:password@backup_db:5432/pgbackweb?sslmode=disable
    depends_on:
      backup_db:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - server

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    profiles:
      - server

  redis:
    container_name: redis
    image: "redis:8-alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
    profiles:
      - server

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
    profiles:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana
    profiles:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    profiles:
      - monitoring

volumes:
  pgdata: {}
  backup_pgdata: {}
  backups: {}
  redis_data: {}
  prometheus_data: {}
  grafana_data: {}
