-- Your SQL goes here
CREATE TYPE MuscleGroup AS ENUM (
    'chest',
    'shoulders',
    'biceps',
    'triceps',
    'forearms',
    'upper_back',
    'lower_back',
    'lats',
    'abs',
    'obliques',
    'quads',
    'hamstrings',
    'calves',
    'glutes'
);

CREATE TYPE ExerciseType AS ENUM (
    'strength',
    'cardio',
    'flexibility',
    'plyometric',
    'bodyweight'
);

CREATE TYPE Equipment AS ENUM (
    'barbell',
    'dumbbell',
    'kettlebell',
    'machine',
    'cable',
    'bodyweight',
    'resistance_band',
    'other'
);

-- Private: Exercises will be generated by me
CREATE TABLE exercises (
    "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL DEFAULT (''),
    "instructions" TEXT NOT NULL DEFAULT (''),
    "equipment" Equipment NOT NULL,
    "difficulty" Difficulty NOT NULL,
    "muscle_group" MuscleGroup NOT NULL,
    "sets" INT NOT NULL DEFAULT (3),
    "reps" INT NOT NULL DEFAULT (12),
    "rest_time" INT NOT NULL DEFAULT (60),
    "exercise_type" ExerciseType NOT NULL,
    "image_url" TEXT NOT NULL DEFAULT (''),
    "video_url" TEXT NOT NULL DEFAULT (''),
    "created_at" TIMESTAMP NOT NULL DEFAULT (now()),
    "updated_at" TIMESTAMP NOT NULL DEFAULT (now())
);

-- Public: Users will log their exercises (sets, reps, etc.) 1 Exercise = 1 Log
CREATE TABLE exercise_logs (
    "id" SERIAL PRIMARY KEY,
    "user_id" UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "exercise_id" BIGINT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    "sets_completed" INT NOT NULL,
    "reps_completed" INT NOT NULL,
    "date" TIMESTAMP NOT NULL DEFAULT (now()),
    "updated_at" TIMESTAMP NOT NULL DEFAULT (now())
);
