global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: 'production'

  - job_name: "protein"
    static_configs:
      - targets: ["api:8000"]
        labels:
          group: 'production'

  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['uptime-kuma:3001']
    basic_auth:
      password_file: uptime_kuma.pwd
